### ISSUE TITLE
Improvement: Title and fav icon.

### ISSUE THREAD

**Issue by MrFaul** [igorlogius/auto-updating-bookmark#3]
I like the add-on it is ideal for browsing documentations / tutorials / MD books.
But since it immediately and only fires on an URL change it often is unable to grab the title and fav icon.

So could you please add a callback that fires again once the tab is fully loaded and updates title and fav icon?

**Comment by igorlogius** [comment]
Hello. 
Thanks for taking the time to write this ticket. 

I'll take the incorrect / missing setting of the title as a bug. 
Should be fixed in version `1.6.8`. 

Regarding the favicons, AFAIK those can not be set via the addon API. ( ref. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/update ) 
I'll still check what i can do ... i seem to remember there was an addon, which claimed to be able to update bookmark favicons, i'll take a look and see if i can find it again and see if the method is something that would make sense to copy and apply here.

**Comment by igorlogius** [comment]
@MrFaul 

Update: i found the addon (ref. https://addons.mozilla.org/en-US/firefox/addon/checkmarks-web-ext/ ) but as far as i can see it really just opens the bookmark into an background tab to trigger the browser built-in loading/updating mechanic of the fav icons. (ref. https://github.com/tanwald/checkmarks/blob/master/sidebar/checkmarks-sidebar.js#L661 ) 

An approch like this would definitely increase the browsers resouce usage (even if i could add some clever delay and idel timers to not cause any immediate issues), i dont feel quite comfortable with adding this as a default function at the moment. 

But if you feel strongly about this ... let me now and i might consider adding a options that would allow you to enable a such a function with the mentioned tradeoffs then you could test if the feature warrents it additional resources on your system.

**Comment by MrFaul** [comment]
Thx mate for fixing this so quickly and naaaa, fav icons aren't that important.

Titles are, i.e. a lot of different MD books can be hosted on the same domain so you really need to look at them to figure out what is what.
That's fixed now 👍
